NDefines.NGame.START_DATE = "11.1.1.12"
NDefines.NGame.END_DATE = "115.1.1.1"
NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.0
NDefines.NNavy.NAVAL_RANGE_TO_INGAME_DISTANCE = 1
NDefines.NTrade.NAVAL_ROUTE_ACCESS_AVOID_COST_MULT = 1000